### ISSUE TITLE
Test failures with HPE MPT

### ISSUE THREAD

**Issue by mmiesch** [JCSDA/jedi-stack#60]
Something that bump is doing through eckit's MPI functionality is causing problems when JEDI is build with HPE MPT as the MPI library.  I know this occurs with version 19.0.5 of the intel compiler suite on Cheyenne and version 2.19 of MPT - I'm not sure if it also occurs for other compilers and versions.  I'm putting this in the icebox for now because this problem does not occur for intel mpi so users who want to use intel compilers do have an alternative.  Furthermore, not many other systems use HPE MPT.  So, it is not urgent.

~~~~~
MPT: 0x00002ae10da4f6da in waitpid () from /glade/u/apps/ch/os/lib64/libpthread.so.0
MPT: Missing separate debuginfos, use: zypper install glibc-debuginfo-2.22-49.16.x86_64
MPT: (gdb) #0  0x00002ae10da4f6da in waitpid ()
MPT:    from /glade/u/apps/ch/os/lib64/libpthread.so.0
MPT: #1  0x00002ae10e8ccdb6 in mpi_sgi_system (
MPT: #2  MPI_SGI_stacktraceback (
MPT:     header=header@entry=0x7ffcac9a2160 "MPT ERROR: Rank 0(g:0) is aborting with error code 1.\n\tProcess ID: 30447, Host: r1i4n8, Program: /glade/work/miesch/jedi/ufo-bundle/build/bin/bump.x\n\tMPT Version: HPE MPT 2.19  02/23/19 05:30:09\n") at sig.c:340
MPT: #3  0x00002ae10e815419 in print_traceback (ecode=ecode@entry=1) at abort.c:246
MPT: #4  0x00002ae10e8156ea in PMPI_Abort (comm=<optimized out>, errorcode=1)
MPT:     at abort.c:68
MPT: #5  0x00002ae10b9251cc in eckit::mpi::Parallel::abort(int) const ()
MPT:    from /glade/work/miesch/jedi/ufo-bundle/build/bin/../lib/libeckit_mpi.so
MPT: #6  0x00002ae103653a11 in type_mpl_mp_mpl_abort_ ()
MPT:    from /glade/work/miesch/jedi/ufo-bundle/build/bin/../lib/libsaber.so
MPT: #7  0x00002ae1036532e7 in type_mpl_mp_mpl_ncerr_ ()
MPT:    from /glade/work/miesch/jedi/ufo-bundle/build/bin/../lib/libsaber.so
MPT: #8  0x00002ae10364fa46 in type_mpl_mp_mpl_ncdimcheck_ ()
MPT:    from /glade/work/miesch/jedi/ufo-bundle/build/bin/../lib/libsaber.so
MPT: #9  0x00002ae1034c8672 in type_io_mp_io_fld_write_ ()
MPT:    from /glade/work/miesch/jedi/ufo-bundle/build/bin/../lib/libsaber.so
MPT: #10 0x00002ae103492be5 in type_diag_mp_diag_write_ ()
MPT:    from /glade/work/miesch/jedi/ufo-bundle/build/bin/../lib/libsaber.so
MPT: #11 0x00002ae103487c23 in type_diag_mp_diag_correlation_ ()
MPT:    from /glade/work/miesch/jedi/ufo-bundle/build/bin/../lib/libsaber.so
MPT: #12 0x00002ae1034c45dc in type_hdiag_mp_hdiag_run_hdiag_ ()
MPT:    from /glade/work/miesch/jedi/ufo-bundle/build/bin/../lib/libsaber.so
MPT: #13 0x00002ae10341330d in type_bump_mp_bump_run_drivers_ ()
MPT:    from /glade/work/miesch/jedi/ufo-bundle/build/bin/../lib/libsaber.so
MPT: #14 0x0000000000454382 in bump_main_f90 ()
MPT: #15 0x000000000044d61f in main ()
MPT: (gdb) A debugging session is active.
MPT:
MPT:    Inferior 1 [process 30447] will be detached.
MPT:
MPT: Quit anyway? (y or n) [answered Y; input not from terminal]
MPT: Detaching from program: /proc/30447/exe, process 30447
~~~~~

**Comment by svahl991** [comment]
Hi @mmiesch 
I've been continuing to work some on trying to get mpas-bundle to work on Cheyenne with some compiler/mpi other than the gnu-openmpi configuration which is where all our work has been done. My hope is that the ['hanging' problem](https://github.com/JCSDA/mpas-jedi/issues/201) we encounter, which we believe might be related to PIO, might not be present with a different MPI implementation.

I'm told that mpt is the most tested mpi implementation with MPAS on Cheyenne. However, due to the issue documented here, we cannot use the Cheyenne jedi modules that involve mpt.

So I'd been working off and on to try to get the intel-impi modules to work with mpas-bundle. However, last week @MiCurry and I came to the conclusion that PIO (and so MPAS) does not appear to work with impi.

So it seems like we're sort of stuck regarding getting mpas-bundle to work with any other MPI implementation on Cheyenne. We cannot use mpt because of BUMP and we cannot use impi because of PIO.

This situation is documented in [this mpas-jedi zenhub issue](https://github.com/JCSDA/mpas-jedi/issues/240).

I don't know if this situation makes this issue important enough to take out of the icebox, but I thought I'd at least mention it.

**Comment by mmiesch** [comment]
Hi @svahl991 - Ok, I'll move this out of the icebox.  When I checked with CISL, they recommended just using impi so I don't think mpt is preferred from a performance standpoint on Cheyenne.  But, I understand that this is what MPAS/PIO use so I'll take a look at this when I can.

**Comment by svahl991** [comment]
Thanks @mmiesch . I also intend to look some more into the problem with PIO and impi as well to see if I can get that to budge.

**Comment by svahl991** [comment]
We were discussing this issue in our MPAS group this morning. Someone suggested that, given all the work that has happened with eckit and saber since this issue was last investigated, maybe there was a chance this issue may no longer exist. Maybe worth re-testing sometime?

In the MPAS group we have (somewhat accidentally) discovered that most of our "hanging" issues do not occur if we build PIO in Debug instead of Release mode. But we do still see issues occasionally which we can't explain, which is what made me think of this MPT issue. It's still not urgent though.
